version: '3'

services:
  mongodb:
    image: mongo:latest
    command: --serviceExecutor adaptive
    ports:
      - '27017:27017'

  redisdb:
    image: redis:latest
    ports:
      - '6379:6379'

  api:
    container_name: pety_api
    restart: on-failure
    build: .
    command: bash -c "rm -rf ./gin-bin && gin -a 8080 --all -i run main.go"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redisdb
